### ISSUE TITLE
CI tries to to test apps with secrets

### ISSUE THREAD

**Issue by nictuku** [yourbase/yourbase#19]
What should we do when an app has secrets? Should the CI try to build and test it?

The CI uses the Bazel rules so it tries to read the secrets from /secrets. That currently fails. We should consider:

- giving it access to the secrets it needs (by allowing k8s to mount secrets as a volume)
- making it skip building things that need secrets
- improve the failure mode / error message.

**Comment by kbfastcat** [comment]
option to skip secrets, and to process secrets in the configuration.

**Comment by nictuku** [comment]
This didn't really work yet.

```
(12:23:09) ERROR: /Users/yves/src/github.com/yourbase/yourbase/ci/BUILD.bazel:24:1: error executing shell command: 'set -e; bazel-out/host/bin/external/jsonnet/cmd/jsonnet -J . --var 'secret_name'='github' bazel-out/darwin-fastbuild/genfiles/ci/github_secret.jsonnet -o bazel-out/darwin-fastbuild/bin/ci/ci_server...' failed (Exit 1)
RUNTIME ERROR: Couldn't open import "external/secrets//github.jsonnet": No match locally or in the Jsonnet library paths.
```
