### ISSUE TITLE
Implement logging infrastructure

### ISSUE THREAD

**Issue by nictuku** [yourbase/yourbase#8]
We need a logging infra that:

- collects logs from services
- provides a CLI interface for querying logs across pods and services
- goes along nicely with the rest of our infra. i.e: this logging system should be simple to deploy and scale so it can be managed by YourBase tools.

Possible candidates:

- oklog
- logging server that uses cockroachdb in the backend

Both oklog and cockroachdb supposedly scale horizontally and seem like a good fit for YourBase infra. oklog is a specialized system, but perhaps less mature.

It's important that users must be able to replace this default logging infrastructure with their own fancier version - for example, it should be easy for them to move to Splunk, logz.io, etc.

**Comment by kbfastcat** [comment]
can we just do logging to stdout, and use docker logging to send it somewhere?  I seem to remember an option for that.

**Comment by nictuku** [comment]
Yes, that's an option. In k8s land, a container running in the same pod can take care of collecting logs from stdout and stdeer. Fluentd is often used for that. But where to send the data - that's the critical question.

**Comment by nictuku** [comment]
I went with ELK rather than oklog or cockroachdb. It's clearly a better fit and it's the industry standard. The only gotcha is that Helm currently exists outside our source tree and by default gets versioned separately. I'll solve that later, by making helm charts hermetic in our source tree.

I think the present issue is done. Bits missing will go in separate issues, like #24.
